### ISSUE TITLE
Errors in collaboration project.

### ISSUE THREAD

**Issue by naveenknethra** [chandniprasad/collaboration-web-site-#1]
![screenshot 659](https://cloud.githubusercontent.com/assets/20578522/20586895/e2f0d790-b22e-11e6-8a3b-57be9e7bc016.png)
![screenshot 840](https://cloud.githubusercontent.com/assets/20578522/20586896/e2f471fc-b22e-11e6-9adf-e11447986be9.png)
![screenshot 841](https://cloud.githubusercontent.com/assets/20578522/20586897/e2f77294-b22e-11e6-950b-e5da43877bd4.png)
![screenshot 842](https://cloud.githubusercontent.com/assets/20578522/20586898/e2fc172c-b22e-11e6-819c-9a07e2590c28.png)
![screenshot 843](https://cloud.githubusercontent.com/assets/20578522/20586899/e300ecc0-b22e-11e6-8a53-f7b0a68753d9.png)
![screenshot 844](https://cloud.githubusercontent.com/assets/20578522/20586900/e304a5a4-b22e-11e6-9c40-e737f582439f.png)
![screenshot 845](https://cloud.githubusercontent.com/assets/20578522/20586901/e326366a-b22e-11e6-8008-f206ac111ad1.png)
![screenshot 846](https://cloud.githubusercontent.com/assets/20578522/20586902/e3297b72-b22e-11e6-88a2-aa8945a26aa1.png)
![screenshot 881](https://cloud.githubusercontent.com/assets/20578522/20586903/e32d9ba8-b22e-11e6-80b8-524c0d7ba640.png)
![screenshot 882](https://cloud.githubusercontent.com/assets/20578522/20586904/e33523b4-b22e-11e6-8d49-288599e13d69.png)
![screenshot 883](https://cloud.githubusercontent.com/assets/20578522/20586906/e33d4a30-b22e-11e6-9b89-2891d5795992.png)
![screenshot 884](https://cloud.githubusercontent.com/assets/20578522/20586905/e33d62ea-b22e-11e6-822e-4fa41196d896.png)
![screenshot 885](https://cloud.githubusercontent.com/assets/20578522/20586907/e35ac632-b22e-11e6-897f-85996407b6e1.png)
![screenshot 886](https://cloud.githubusercontent.com/assets/20578522/20586908/e35d8d18-b22e-11e6-91c9-b7e71796d99b.png)
![screenshot 887](https://cloud.githubusercontent.com/assets/20578522/20586909/e3636c74-b22e-11e6-94ff-a83449868235.png)
![screenshot 888](https://cloud.githubusercontent.com/assets/20578522/20586910/e36b8a6c-b22e-11e6-8b4e-984d24790e46.png)
![screenshot 889](https://cloud.githubusercontent.com/assets/20578522/20586911/e377e32a-b22e-11e6-8385-6aaea2e4c8cb.png)
![screenshot 890](https://cloud.githubusercontent.com/assets/20578522/20586912/e378fe4a-b22e-11e6-8338-05503cebc09c.png)
![screenshot 891](https://cloud.githubusercontent.com/assets/20578522/20586913/e397e9e0-b22e-11e6-9030-9ddce6126916.png)
![screenshot 892](https://cloud.githubusercontent.com/assets/20578522/20586914/e39bae5e-b22e-11e6-8998-4c7dd8ac2b10.png)
![screenshot 893](https://cloud.githubusercontent.com/assets/20578522/20586915/e39dd152-b22e-11e6-9ccd-fd12b4d456e6.png)
![screenshot 894](https://cloud.githubusercontent.com/assets/20578522/20586916/e3a3448e-b22e-11e6-817b-39105a46d5fa.png)
![screenshot 898](https://cloud.githubusercontent.com/assets/20578522/20586917/e3b03cd4-b22e-11e6-989c-2c856088f55e.png)
![screenshot 899](https://cloud.githubusercontent.com/assets/20578522/20586918/e3b3ce76-b22e-11e6-87b6-4026cfc1c249.png)
![screenshot 900](https://cloud.githubusercontent.com/assets/20578522/20586919/e3cc4de8-b22e-11e6-94f3-cb5951196f1c.png)
![screenshot 901](https://cloud.githubusercontent.com/assets/20578522/20586920/e3d0a780-b22e-11e6-9dd1-bc4564ced91a.png)
![screenshot 902](https://cloud.githubusercontent.com/assets/20578522/20586921/e3d30278-b22e-11e6-86bc-a0f1131609f9.png)
![screenshot 903](https://cloud.githubusercontent.com/assets/20578522/20586922/e3dafe38-b22e-11e6-8b88-271c3bf62696.png)
![screenshot 904](https://cloud.githubusercontent.com/assets/20578522/20586923/e3e85380-b22e-11e6-9f6e-4c59f3a72529.png)
![screenshot 905](https://cloud.githubusercontent.com/assets/20578522/20586924/e3ec3afe-b22e-11e6-8669-2497965ceb96.png)
![screenshot 906](https://cloud.githubusercontent.com/assets/20578522/20586925/e4073b74-b22e-11e6-8e30-7249e494b25d.png)
![screenshot 907](https://cloud.githubusercontent.com/assets/20578522/20586926/e409d532-b22e-11e6-945c-d3fc1354239e.png)
![screenshot 908](https://cloud.githubusercontent.com/assets/20578522/20586927/e417ec1c-b22e-11e6-824e-3011ae7e5863.png)
![screenshot 909](https://cloud.githubusercontent.com/assets/20578522/20586928/e41f1d66-b22e-11e6-8ab5-21cef7f323cf.png)
![screenshot 910](https://cloud.githubusercontent.com/assets/20578522/20586929/e423d720-b22e-11e6-8867-6d4fcc0b2e5f.png)
![screenshot 911](https://cloud.githubusercontent.com/assets/20578522/20586930/e4246d7a-b22e-11e6-8d9d-ee6d210bc276.png)
![screenshot 912](https://cloud.githubusercontent.com/assets/20578522/20586931/e4442ae8-b22e-11e6-9a8b-d1e969251caf.png)
![screenshot 913](https://cloud.githubusercontent.com/assets/20578522/20586932/e4477298-b22e-11e6-80a8-d269c2b388db.png)
![screenshot 914](https://cloud.githubusercontent.com/assets/20578522/20586934/e458c8ae-b22e-11e6-8623-168f7ddd74c9.png)
![screenshot 915](https://cloud.githubusercontent.com/assets/20578522/20586935/e45d214c-b22e-11e6-8fd9-0cee95ca1fc1.png)
![screenshot 916](https://cloud.githubusercontent.com/assets/20578522/20586936/e462babc-b22e-11e6-8c05-c688e2c82770.png)
![screenshot 917](https://cloud.githubusercontent.com/assets/20578522/20586937/e465f97a-b22e-11e6-8fd5-5753408e5c2d.png)
![screenshot 918](https://cloud.githubusercontent.com/assets/20578522/20586938/e47c022e-b22e-11e6-8447-a12f6d270479.png)
![screenshot 919](https://cloud.githubusercontent.com/assets/20578522/20586939/e487f21e-b22e-11e6-8681-b22a317aa9de.png)
![screenshot 920](https://cloud.githubusercontent.com/assets/20578522/20586940/e4a1abbe-b22e-11e6-8f26-094c1f2b554d.png)
![screenshot 921](https://cloud.githubusercontent.com/assets/20578522/20586941/e4a546ca-b22e-11e6-86f7-34f1dbf02398.png)
![screenshot 922](https://cloud.githubusercontent.com/assets/20578522/20586942/e4a9d53c-b22e-11e6-97ff-f455da200c33.png)
![screenshot 923](https://cloud.githubusercontent.com/assets/20578522/20586943/e4ad1350-b22e-11e6-8009-01c5e8032280.png)
![screenshot 924](https://cloud.githubusercontent.com/assets/20578522/20586944/e4cebab4-b22e-11e6-91b4-5ea3854be148.png)
![screenshot 925](https://cloud.githubusercontent.com/assets/20578522/20586945/e4ddca04-b22e-11e6-892c-d0418eb94320.png)
![screenshot 927](https://cloud.githubusercontent.com/assets/20578522/20586946/e502771e-b22e-11e6-85eb-f4e389c525f8.png)
![screenshot 928](https://cloud.githubusercontent.com/assets/20578522/20586947/e506e61e-b22e-11e6-9f7e-0f683e3b5bd9.png)
![screenshot 929](https://cloud.githubusercontent.com/assets/20578522/20586948/e510666c-b22e-11e6-97eb-c123f3b2e384.png)
![screenshot 930](https://cloud.githubusercontent.com/assets/20578522/20586949/e514e494-b22e-11e6-9611-4c9dc8d7c400.png)

**Comment by chandniprasad** [comment]
![screenshot 937](https://cloud.githubusercontent.com/assets/20518306/20858311/68cf10d4-b969-11e6-8140-bbfb50e232b0.png)
![screenshot 938](https://cloud.githubusercontent.com/assets/20518306/20858313/68d21c02-b969-11e6-909e-b6fa97bad7e7.png)
![screenshot 942](https://cloud.githubusercontent.com/assets/20518306/20858312/68d1e426-b969-11e6-83b0-adca2772cdc2.png)
![screenshot 944](https://cloud.githubusercontent.com/assets/20518306/20858314/6906dabe-b969-11e6-81a3-e4000a3542ae.png)
